export const CONTRACT_TRACKER_TIME_STARTED       = 'CONTRACT_TRACKER_TIME_STARTED';
export const CONTRACT_TRACKER_TIME_STOPPED       = 'CONTRACT_TRACKER_TIME_STOPPED';
export const CONTRACT_TRACKER_TIME_SUCCESS       = 'CONTRACT_TRACKER_TIME_SUCCESS';
export const CONTRACT_TRACKER_TIME_FAIL       = 'CONTRACT_TRACKER_TIME_FAIL'; 